using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CilComplexityAnalyzer.TestGenerator;

[Generator]
public class TestSuiteGenerator : IIncrementalGenerator
{
    private const string TestSuiteBaseFullName = "CilComplexityAnalyzer.TestExecutor.Contract.TestSuiteBase";
    private const string TestCaseBaseFullName = "CilComplexityAnalyzer.TestExecutor.Contract.TestCaseBase";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var suites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax, // { BaseList: not null },
                transform: static (ctx, _) => GetSuiteOrNull(ctx))
            .Where(static suite => suite is not null)
            .Select(static (suite, _) => suite!)
            .Collect();
        context.RegisterPostInitializationOutput(ctx => 
        {
            ctx.AddSource("GeneratorDebug.g.cs", "// Generator dziala!");
        });

        context.RegisterSourceOutput(suites, Generate);
    }

    private static SuiteInfo? GetSuiteOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not { } suiteSymbol)
            return null;

        if (!InheritsFrom(suiteSymbol, TestSuiteBaseFullName))
            return null;

        var cases = suiteSymbol.GetTypeMembers()
            .Where(t => InheritsFrom(t, TestCaseBaseFullName))
            .Select(GetCaseInfo)
            .ToImmutableArray();

        var isContainerized = suiteSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.Name is "IsContainerizedAttribute" or "IsContainerized");

        var nameAttr = suiteSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "NameAttribute" or "Name");
        
        var name = nameAttr?.ConstructorArguments.FirstOrDefault().Value as string;

        return new SuiteInfo(
            Namespace: suiteSymbol.ContainingNamespace.ToDisplayString(),
            ClassName: suiteSymbol.Name,
            Name: string.IsNullOrWhiteSpace(name) ? suiteSymbol.Name : name!,
            IsContainerized: isContainerized,
            Cases: cases);
    }

    private static CaseInfo GetCaseInfo(INamedTypeSymbol caseSymbol)
    {
        var settings = caseSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "CaseSettingsAttribute" or "CaseSettings" or "TestSettingsAttribute" or "TestSettings" or "SecretTestName");

        long instructionCap = GetInstructionCap(settings, 1_000_000L);
        //var classDecl = caseSymbol.DeclaringSyntaxReferences.First().GetSyntax();
        //var fullSource = classDecl.ToFullString();
        //long timeoutMs = GetNamedArg(settings, "TimeoutMs", 30_000L);
        //int memoryMb = (int)GetNamedArg(settings, "MemoryMb", 512L);

        return new CaseInfo(caseSymbol.Name, instructionCap);
    }

    private static long GetInstructionCap(AttributeData? attr, long fallback)
    {
        if (attr is null) return fallback;

        var namedArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "InstructionCap");
        if (namedArg.Value.Value is not null)
            return Convert.ToInt64(namedArg.Value.Value);

        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is not null)
            return Convert.ToInt64(attr.ConstructorArguments[0].Value);

        return fallback;
    }

    private static bool InheritsFrom(INamedTypeSymbol? symbol, string fullyQualifiedBaseName)
    {
        for (var baseType = symbol?.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            var fullName = $"{baseType.ContainingNamespace.ToDisplayString()}.{baseType.Name}";
            if (fullName == fullyQualifiedBaseName)
                return true;
        }
        return false;
    }
    
    private static void Generate(SourceProductionContext spc, ImmutableArray<SuiteInfo> suites)
    {
        foreach (var suite in suites)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using ExecEngine = global::CilComplexityAnalyzer.TestExecutor.TestExecutor;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(suite.Namespace) && suite.Namespace != "<global namespace>")
            {
                sb.AppendLine($"namespace {suite.Namespace};");
                sb.AppendLine();
            }

            sb.AppendLine("[TestClass]");
            sb.AppendLine($"public partial class {suite.ClassName}_Tests");
            sb.AppendLine("{");
            sb.AppendLine("    private static List<string> _results = new List<string>();");
            sb.AppendLine("    private TestExecutor? _executor;");
            sb.AppendLine();
            sb.AppendLine("    [ClassInitialize]");
            sb.AppendLine("    public static void Initialize(TestContext context)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var suiteInstance = new {suite.ClassName}();");
            //sb.AppendLine($"        var testResults = ExecEngine.Execute(suiteInstance);");
            sb.AppendLine("    }");
            sb.AppendLine();

            var numberOfTests = 0;
            foreach (var testCase in suite.Cases)
            {
                sb.AppendLine("    [TestMethod]");
                sb.AppendLine($"    public async Task {testCase.Name}()");
                sb.AppendLine("    {");
                sb.AppendLine();
                sb.AppendLine($"        var testResult = await _executor.GetResult(\"{testCase.Name}\");");
                sb.AppendLine();
                sb.AppendLine($"        _results[{numberOfTests}] = \"Success\";");
                sb.AppendLine("        var typeName = testResult.GetType().Name;");
                sb.AppendLine("        if (typeName == \"Failure\")");
                sb.AppendLine("        {");
                sb.AppendLine("            var message = testResult.GetType().GetProperty(\"Message\")?.GetValue(testResult)?.ToString() ?? \"Unknown failure\";");
                sb.AppendLine($"            _results[{numberOfTests}] = message;");
                sb.AppendLine($"            Assert.Fail($\"Test '{testCase.Name}' zakończył się niepowodzeniem: {{message}}\");");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                numberOfTests++;
            }

            sb.AppendLine("}");

            spc.AddSource($"{suite.ClassName}Tests.g.cs", sb.ToString());
        }
    }

    private sealed record SuiteInfo(
        string Namespace, string ClassName, string Name, bool IsContainerized,
        ImmutableArray<CaseInfo> Cases)
    {
        public string Namespace { get; } = Namespace;
        public string ClassName { get; } = ClassName;
        public string Name { get; } = Name;
        public bool IsContainerized { get; } = IsContainerized;
        public ImmutableArray<CaseInfo> Cases { get; } = Cases;
    }

    private sealed record CaseInfo(string Name,long InstructionCap)
    {
        public string Name { get; } = Name;
        public long InstructionCap { get; } = InstructionCap;
    }
}