using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CilComplexityAnalyzer.Facade;

[Generator]
public class TestSuiteGenerator : IIncrementalGenerator
{
    private const string TestSuiteBaseFullName = "CilComplexityAnalyzer.TestExecutor.Contract.TestSuite";
    private const string TestCaseBaseFullName = "CilComplexityAnalyzer.TestExecutor.Contract.TestCase";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var suites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax, 
                transform: static (ctx, _) => GetSuiteOrNull(ctx))
            .Where(static suite => suite is not null)
            .Select(static (suite, _) => suite!)
            .Collect();

        context.RegisterSourceOutput(suites, Generate);
    }

    private static SuiteInfo? GetSuiteOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not { } suiteSymbol)
            return null;

        if (suiteSymbol.DeclaredAccessibility != Accessibility.Public)
            return null;

        if (suiteSymbol.ContainingType is not null)
            return null;

        if (suiteSymbol.IsAbstract || !InheritsFrom(suiteSymbol, TestSuiteBaseFullName))
            return null;

        var testSuiteSource = classDecl.SyntaxTree.ToString();

        var studentAttr = suiteSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "StudentSolutionAttribute" or "StudentSolution");

        string studentSourceCode = string.Empty;

        if (studentAttr is not null && studentAttr.ConstructorArguments.Length > 0)
        {
            if (studentAttr.ConstructorArguments[0].Value is INamedTypeSymbol studentTypeSymbol)
            {
                var syntaxReference = studentTypeSymbol.DeclaringSyntaxReferences.FirstOrDefault();
                if (syntaxReference is not null)
                {
                    studentSourceCode = syntaxReference.SyntaxTree.ToString();
                }
            }
        }

        var cases = suiteSymbol.GetTypeMembers()
            .Where(m => !m.IsAbstract && InheritsFrom(m, TestCaseBaseFullName))
            .Select(m => new CaseInfo(m.Name))
            .ToImmutableArray();

        string ns = suiteSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : suiteSymbol.ContainingNamespace.ToDisplayString();

        string fullClassName = string.IsNullOrEmpty(ns)
            ? suiteSymbol.Name
            : $"{ns}.{suiteSymbol.Name}";

        return new SuiteInfo(
            Namespace: ns,
            ClassName: suiteSymbol.Name,
            FullClassName: fullClassName,
            TestSuiteSource: testSuiteSource,
            StudentSolutionSource: studentSourceCode,
            Cases: cases
        );
    }

    private static bool InheritsFrom(INamedTypeSymbol? symbol, string fullyQualifiedBaseName)
    {
        for (var baseType = symbol?.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (baseType.ToDisplayString() == fullyQualifiedBaseName)
                return true;
        }
        return false;
    }
    
    private static void Generate(SourceProductionContext spc, ImmutableArray<SuiteInfo> suites)
    {
        foreach (var suite in suites)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using CilComplexityAnalyzer.TestExecutor.Contract.Results;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(suite.Namespace) && suite.Namespace != "<global namespace>")
            {
                sb.AppendLine($"namespace {suite.Namespace};");
                sb.AppendLine();
            }

            sb.AppendLine($"public partial class {suite.ClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public override string StudentSolutionSourceCode() => \"\"\"");
            sb.AppendLine(suite.StudentSolutionSource);
            sb.AppendLine("\"\"\";");
            sb.AppendLine();
            sb.AppendLine("    public override string TestSuiteSourceCode() => \"\"\"");
            sb.AppendLine(suite.TestSuiteSource);
            sb.AppendLine("\"\"\";");
            sb.AppendLine("}");
            sb.AppendLine();
            
            sb.AppendLine("[TestClass]");
            sb.AppendLine($"public partial class {suite.ClassName}_Tests");
            sb.AppendLine("{");
            sb.AppendLine($"    private static {suite.FullClassName} _suite = default!;");
            sb.AppendLine("    private static global::CilComplexityAnalyzer.TestExecutor.TestExecutor _executor = default!;");
            sb.AppendLine();
            sb.AppendLine("    [ClassInitialize]");
            sb.AppendLine("    public static void Initialize(TestContext context)");
            sb.AppendLine("    {");
            sb.AppendLine($"        _suite = new {suite.FullClassName}();");
            sb.AppendLine($"        _executor = new global::CilComplexityAnalyzer.TestExecutor.TestExecutor(_suite);");
            sb.AppendLine($"        _executor.BeginExecution();");
            sb.AppendLine("    }");
            sb.AppendLine();

            for (int i = 0; i < suite.Cases.Length; i++)
            {
                var testCase = suite.Cases[i];
                sb.AppendLine("    [TestMethod]");
                sb.AppendLine($"    public async Task {testCase.Name}()");
                sb.AppendLine("    {");
                sb.AppendLine($"         var result = await _executor.GetResult({i});");
                sb.AppendLine($"         if (result.IsT1)");
                sb.AppendLine("         {");
                sb.AppendLine("             var failure = result.AsT1;");
                sb.AppendLine("             Assert.Fail(failure.Message ?? \"Test failed\");");
                sb.AppendLine("         }");
                sb.AppendLine("    }");

                if (i < suite.Cases.Length - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");

            spc.AddSource($"{suite.ClassName}Tests.g.cs", sb.ToString());
        }
    }

    private sealed record SuiteInfo(
        string Namespace,
        string ClassName,
        string FullClassName,
        string TestSuiteSource,
        string StudentSolutionSource,
        ImmutableArray<CaseInfo> Cases
    );

    private sealed record CaseInfo(
        string Name
        /*
        long InstructionCap,
        string? MethodName,
        Location? Location
         */
    );
}